version: '3.9'

services:

  vtj:
    build:
      context: .
      target: dev
    container_name: vtj
    ports:
      - "4173:4173"
      - "5173:5173"
    stdin_open: true
    tty: true
    volumes:
    #   - ./public:/var/www/public
      - ./src:/var/www/src
    #   - ./node_modules:/var/www/node_modules
    #   - ./env.d.ts:/var/www/env.d.ts
    #   - ./index.html:/var/www/index.html
    #   - ./package-lock.json:/var/www/package-lock.json
    #   - ./package.json:/var/www/package.json
    #   - ./tsconfig.app.json:/var/www/tsconfig.app.json
    #   - ./tsconfig.json:/var/www/tsconfig.json
    #   - ./tsconfig.node.json:/var/www/tsconfig.node.json
    #   - ./vite.config.ts:/var/www/vite.config.ts
    #   - ./__tests__:/var/www/__tests__
    #   - ./vitest.config.ts:/var/www/vitest.config.ts
    #   - ./tsconfig.vitest.json:/var/www/tsconfig.vitest.json
